**Question 1:**  ...should you choose to accept it*
You are supposed to write an algorithm to dehaze images.<br>
You are given this paper:
https://arxiv.org/pdf/1601.07661.pdf
* What is this website ?
* What are the main takeaway ideas ?
* Which field of AI is it dealing with ?
* Do you have coffee nearby ?


**Question 2:** *It all starts with a git clone*
<br>You come across this repository:
* https://github.com/thuBingo/DehazeNet_Pytorch

Like always the code is not commented
  * Where do you start ?

**Question 3:** *relative paths, absolute paths...*
* What is relative path vs hardcoded path ? Should you use one 


vs the other?
* Can you comment the code and make it usable with relative paths

**Question 4:** *the good hunter and the bad hunter*

All the code is in 1 file, how can we re-organize the code?
Can we reorganize it in 3 files ?
  * data processing
  * model training
  * model evaluation
  * How are you going to deal with the imports?

**Question5** : *Don't worry if you don't understand Andrew NG*

When it comes to dehazing there are 5 relevant features
* According to the paper what are these relevant features ?

How to read one paper (Andrew NG) ?<br>
**Don't start from the first page and finish at last one
Read it in multiple passes**<br>
1. Read the title, abstracts, figures, experiments
2. Go through conclusion, Figures and skip the rest
3. Read the rest but skip the math
4. Read whole but skip the parts that don't make sense.

**Question 6:** *What did I just read?*
* According to what you have read
  * What is the goal of the neural network -
classification ? regression ?
  * according to the code  What is the goal of the code - classification ? regression ?

**Question7**: *a bit of jargon*
<br>
(Please provide an example for each question)
* What is a "weights" file ? 
* What is a pickle file ?
* What is *defog4_noaug.pth* ?

**Question 8:** *good code is like art... or not*
<br>
In the defog function below you can see many statements:
* Can you explain what the function actually does ?
* Is it an efficient way to write code ?
* what does the code below mean ?
* Can you propose a more efficient way ? no more for loop
https://stackoverflow.com/questions/31527755/extract-blocks-or-patches-from-numpy-array


In [8]:
import numpy as np
A= np.array(range(625)).reshape(25,25)
print(A[::5,::5])

[[  0   5  10  15  20]
 [125 130 135 140 145]
 [250 255 260 265 270]
 [375 380 385 390 395]
 [500 505 510 515 520]]


In [ ]:
def defog(pic_dir):
	img = Image.open(pic_dir)
	img1 = loader(img)
	img2 = transforms.ToTensor()(img)
	c, h, w = img1.shape
	patch_size = 16
	num_w = int(w / patch_size)
	num_h = int(h / patch_size)
	t_list = []
	for i in range(0, num_w):
		for j in range(0, num_h):
			patch = img1[:, 0 + j * patch_size:patch_size + j * patch_size,
				0 + i * patch_size:patch_size + i * patch_size]
			patch = torch.unsqueeze(patch, dim=0)
			t = net(patch)
			t_list.append([i,j,t])
	
	t_list = sorted(t_list, key=lambda t_list:t_list[2])
	a_list = t_list[:len(t_list)//100]
	a0 = 0
	for k in range(0,len(a_list)):
		patch = img2[:, 0 + a_list[k][1] * patch_size:patch_size + a_list[k][1] * patch_size,
				0 + a_list[k][0] * patch_size:patch_size + a_list[k][0] * patch_size]
		a = torch.max(patch)
		if a0 < a.item():
			a0 = a.item()
	for k in range(0,len(t_list)):
		img2[:, 0 + t_list[k][1] * patch_size:patch_size + t_list[k][1] * patch_size,
			0 + t_list[k][0] * patch_size:patch_size + t_list[k][0] * patch_size] = (img2[:,
			0 + t_list[k][1] * patch_size:patch_size + t_list[k][1] * patch_size,
			0 + t_list[k][0] * patch_size:patch_size + t_list[k][0] * patch_size] - a0*(1-t_list[k][2]))/t_list[k][2]
	defog_img = transforms.ToPILImage()(img2)
	defog_img.save('/home/panbing/PycharmProjects/defog/test/test.jpg')


defog('/home/panbing/PycharmProjects/defog/test/fogpic.jpg')

**Question 09**: *one command that chnaged everything*
* One friend of ours is not 100% sure of his/her Docker skills& shell commands, can you explain what the commands below would do ?


In [1]:
!git clone https://github.com/thuBingo/DehazeNet_Pytorch.git

Cloning into 'DehazeNet_Pytorch'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 22 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.


In [2]:
cd /content/DehazeNet_Pytorch

/content/DehazeNet_Pytorch


In [3]:
mkdir ./dataset

**Question 10:** *copy paste* 

* If you have not cloned  the project, please clone it. what command are you going to use ?
* Your dehazing function should work, how do you update your github  repository

**Question 11**: *kaggle and its open sea of datasets*

* You have been told that there is a great dataset of underwater images available on kaggle.
how do you programmatically download it ?
* Where will you run this command ?
* Is there a problem with colab ?
if yes what is the solution ?

### Describe problem 1

### Describe  problem 2

**Question 12** *GUI, CLI... API*
* What is a CLI?
* What do you need to interact with kaggle CLI ?

In [5]:
# vous uploadez le fichier kaggle.json dans le répertoire : /root/.kaggle
!mkdir /root/.kaggle/
!cp /content/kaggle.json /root/.kaggle/

**Question 13** *kaggle data*
* What are the commands below ?
* What is missing in the second cell ?

In [10]:
!chmod 600 /root/.kaggle/kaggle.json

In [ ]:
!pip uninstall -y kaggle
!pip install --upgrade pip
!pip install kaggle==1.5.6

In [ ]:
kaggle competitions download -c tensorflow-great-barrier-reef

In [14]:
!kaggle competitions download -c tensorflow-great-barrier-reef --force


100% 14.2G/14.2G [01:56<00:00, 86.4MB/s]
100% 14.2G/14.2G [01:56<00:00, 131MB/s] 


**Question 14** *deal with zip*
* Let's assume you unzipped the file in the **WRONG** folder:
  * which command can help you out ?
  * How do you zip a folder ?
  * How do you zip a file ?
  * How many files have you unzipped?
  * Where can you see this info?

In [7]:
 /content/DehazeNet_Pytorch/*.jpg /content/DehazeNet_Pytorch/dataset/

**Question 15** "just import it"

* You want to try the commands in the code: *test.py* (supplied in the aforementionned Github repository)
  * Can you import it as a module ?
  * Do you have to be placed in a particular folder ? 

In [9]:
import create_dataset

100%|██████████| 34/34 [01:11<00:00,  2.11s/it]


* If  you run create_dataset does it work ?

* If you import create_dataset, what happens?

**Question 16:** *important matter*
<br>About import and reload: say you've modified the .py file and you want to reload a cell :

* If you modify the code in the editor can you run python code in Jupyter without reloading ?
* Is there any python commands which let you reload automatically ?

**Question 17:** *module update*
* What is %load_ext autoreload ?
* What is %autoreload 2 ?

In [ ]:
%load_ext autoreload
%autoreload 2
import create_dataset

**Question 18:** *if name =='__main__'*
<br>
In the code you often see "if name =='__main__'. * Is it necessary ?
* what does it do. ?

* what does the command below do ?
  * what does -r mean ?
  * what does -f mean ?

**Question 19:** *with great power comes great responsability*

* Does this statement applies for the command below?
* What does it do ?

In [5]:
!rm -rf  /content/DehazeNet_Pytorch/fogged_dataset

**Question 20:** *Python is so pythonesque*
* What is the language below ?
* What is it doing ?

In [7]:
!ls /content/DehazeNet_Pytorch/fogged_dataset | wc -l

1064286


In [61]:
!cat /content/DehazeNet_Pytorch/path_train.txt | head -10

/content/DehazeNet_Pytorch/fogged_dataset/11110008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/11310008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/12110008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/12410008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/12610008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/12710008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/13310008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/13510008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/13710008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/13810008.jpg


In [57]:
!echo "$(ls -d /content/DehazeNet_Pytorch/fogged_dataset| head -1)/$(ls /content/DehazeNet_Pytorch/fogged_dataset| head -1)" >adder.txt

In [58]:
!cp "$(ls -d /content/DehazeNet_Pytorch/fogged_dataset| head -1)/$(ls /content/DehazeNet_Pytorch/fogged_dataset| head -1)" /content/DehazeNet_Pytorch/test

**Question 21** : *a matter of pixel values*
* You have generated the files and yet you can't see them.
* why is that ?
* How can you check a couple of files ?
* Which commands can you run ? (to see the n first files ?)

**Question 22:** *a matter of imports*

Can you import DehazeNet-pytorch.py ?
* If not why ?
* Does the code work ?
* Can you import a module when there is a mistake/typo?


**Question23**: *Getting them images*

* How to download random image on the  web ?
* What is PIL?
* How do you open an image with 
  * PIL ?
  * opencv ?
  * matplotlib ?

In [66]:
!wget https://cdn.pixabay.com/photo/2019/12/03/20/51/fog-4671042_960_720.jpg

--2022-01-23 19:03:49--  https://cdn.pixabay.com/photo/2019/12/03/20/51/fog-4671042_960_720.jpg
Resolving cdn.pixabay.com (cdn.pixabay.com)... 104.18.20.183, 104.18.21.183, 2606:4700::6812:14b7, ...
Connecting to cdn.pixabay.com (cdn.pixabay.com)|104.18.20.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 135630 (132K) [image/jpeg]
Saving to: ‘fog-4671042_960_720.jpg’

fog-4671042_960_720 100%[===================>] 132.45K  --.-KB/s    in 0.02s   

2022-01-23 19:03:50 (5.67 MB/s) - ‘fog-4671042_960_720.jpg’ saved [135630/135630]



**Question 24**: *say import one more time*
<br>
You want to test the code on an image, will the code below work ?

In [87]:
%load_ext autoreload
%autoreload 2
import DehazeNet_pytorch

/content/DehazeNet_Pytorch/DehazeNet_pytorch.py:45: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  if m.bias is not None:


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


**Question 24**: *AI detected*
* In the code, where is the predictive model declared ?
* We don't want to reexecute longparts of the code all the time, what should we do ? 
  * Is it a good practice to have the code separated in many parts?

**Question 25**: *Hardcoding for life*
* In the code, how is the destination path is defined ?
* Is it correct ?
* What is ARGPARSE ?
  * Can we add argparse parameters to make this code easier to run ?

**Question 25**: *time to smash that button*
<br>
<br>
You might be ready to execute the code.
* Is it working - are you running the code on Colab?
* Why is it not - What happened?

In [ ]:
%load_ext autoreload
%autoreload 2
import DehazeNet_pytorch

 81%|████████  | 27212189/33583973 [00:18<00:04, 1579108.56it/s]

**Question 26**: *My first class*

* Let's define a class named car
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed

Must-read : https://realpython.com/python-super/

**Question 27**: *My second class*

* Have you heard of class inheritance ?$
* Let's define a class named **vehicle**
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed

* Let's define a class named **moto**
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed
* Let's define a class named car
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed

["Simple examples - in case you are stuck"](https://www.edureka.co/blog/inheritance-in-python/)

**Question 28**: *Torch class*
* here is the example
* how would you apply it to this particular example ?

In [88]:
import os
import pandas as pd

from torchvision.io import read_image

# inherits from the Dataset class
class CustomImageDataset(Dataset):

    # init function will be executed when instnatiated
    def __init__(self, annotations_file, img_dir, transform=None, target_transform=None):
        self.img_labels = pd.read_csv(annotations_file)   # attributes
        self.img_dir = img_dir                            # attributes
        self.transform = transform                        # attributes
        self.target_transform = target_transform          # attributes

    # allows you to calculate the length of the instantiated Dataset
    def __len__(self):
        return len(self.img_labels)

    # allows you to  pick 1 element in the dataset
    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.img_labels.iloc[idx, 0])
        image = read_image(img_path)
        label = self.img_labels.iloc[idx, 1]
        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            label = self.target_transform(label)
        return image, label

**Question 29**: *Torch class*
* Here is the example
* How would you apply it to this particular example ?
* please look @ the example below

https://stanford.edu/~shervine/blog/pytorch-how-to-generate-data-parallel

https://medium.com/analytics-vidhya/pytorch-for-deep-learning-feed-forward-neural-network-d24f5870c18

**Question 30**: *Time to nut up or shut up*
* Launch the training !
